---
  tagline:Code'n'Stuff from James Curran, simple country programmer
---
lsi: false
highlighter: true
exclude: [safe]
permalink: /blog/:year/:month/:day/:title/

future:      true
markdown:    kramdown

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
    syntax_highlighter: rouge



maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex



redcarpet:
  extensions: ["gh_blockcode", "fenced_code"]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
