title: Honest Illusion
email: james.curran@gmail.com

lsi: false
exclude: [safe]
permalink: /blog/:year/:month/:day/:title/

url: "https://honestillusion.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

future:      true
markdown:    kramdown

safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

redcarpet:
  extensions: ["fenced_code_blocks"]
  
